export enum Industry {
  AccountingAndTax = 'Accounting & Tax',
  Agriculture = 'Agriculture',
  Automotive = 'Automotive',
  Banking = 'Banking',
  BusinessServicesAndConsulting = 'Business Services & Consulting',
  ComputerAndElectronics = 'Computer and Electronics',
  Construction = 'Construction',
  DesignOrCreativeServices = 'Design/Creative Services',
  Ecommerce = 'Ecommerce',
  Education = 'Education',
  EngineeringAndTechnology = 'Engineering & Technology',
  FinancialServicesAndTechnology = 'Financial Services & Technology',
  Government = 'Government',
  Healthcare = 'Healthcare',
  Hospitality = 'Hospitality',
  Insurance = 'Insurance',
  ITServices = 'IT Services',
  LegalServices = 'Legal Services',
  LifeSciences = 'Life Sciences',
  LogisticsOrTransportation = 'Logistics/Transportation',
  Manufacturing = 'Manufacturing',
  MarketingOrPR = 'Marketing/PR',
  MediaAndEntertainment = 'Media & Entertainment',
  NotForProfit = 'Not for Profit',
  Pharmaceutical = 'Pharmaceutical',
  RealEstate = 'Real Estate',
  Retail = 'Retail',
  TransportationAndWarehousing = 'Transportation & Warehousing',
  Others = 'Others',
}

export enum UserOrganisationRole {
  Administrator = 'Administrator',
  CEO = 'CEO',
  CFO = 'CFO',
  COO = 'COO',
  CofounderAndCXO = 'Cofounder & CXO',
  Executives = 'Executives',
  Finance = 'Finance',
  FounderAndCXO = 'Founder & CXO',
  HR = 'HR',
  IT = 'IT',
  LegalCounsel = 'Legal Counsel',
  OperationsManager = 'Operations Manager',
  ProcurementSpecialist = 'Procurement Specialist',
  SalesRepresentative = 'Sales Representative',
  PartnershipManagers = 'Partnership Managers',
  Others = 'Others',
}
